// Calculator.h
//
// Header for the Calculator TurboModule on iOS.
//
// AppSpecs.h is GENERATED by codegen during the Pod build (from
// src/specs/NativeCalculator.ts). It contains the NativeCalculatorSpec
// protocol that this class must adopt.

#import <AppSpecs/AppSpecs.h>
#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface Calculator : NSObject <NativeCalculatorSpec>
@end

NS_ASSUME_NONNULL_END
