package com.rnarchdemo.calculator

import com.facebook.fbreact.specs.NativeCalculatorSpec
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.annotations.ReactModule

/**
 * Android implementation of the Calculator TurboModule.
 *
 * NativeCalculatorSpec is GENERATED by codegen from
 * src/specs/NativeCalculator.ts at build time. Do not try to import it
 * before running `./gradlew generateCodegenArtifactsFromSchema` or simply
 * building the app.
 */
@ReactModule(name = CalculatorModule.NAME)
class CalculatorModule(reactContext: ReactApplicationContext) :
    NativeCalculatorSpec(reactContext) {

  override fun getName(): String = NAME

  override fun add(a: Double, b: Double): Double = a + b

  override fun multiplyAsync(a: Double, b: Double, promise: Promise) {
    // In production, dispatch to an Executor/coroutine for heavy work.
    Thread {
      try {
        val result = a * b
        promise.resolve(result)
      } catch (e: Exception) {
        promise.reject("CALC_ERROR", e)
      }
    }.start()
  }

  override fun getTypedExportedConstants(): Map<String, Any> =
      mapOf(
          "PI" to Math.PI,
          "E" to Math.E,
      )

  companion object {
    const val NAME = "Calculator"
  }
}
